In [1]:
# using groupby function

In [2]:
#actual syntax is as follows 

# df.groupby( by= None, axis=0, level= None, as_index= True, sort=True, group_keys= True, squeeze= False)

In [5]:
import pandas as pd
nba = pd.read_csv(r'C:\Users\Administrator\Desktop\Python Test Data\nba.csv')

In [6]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [7]:
teammates = nba.groupby('Team')

In [9]:
teammates.first()

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Atlanta Hawks,Kent Bazemore,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
Boston Celtics,Avery Bradley,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Brooklyn Nets,Bojan Bogdanovic,44.0,SG,27.0,6-8,216.0,Oklahoma State,3425510.0
Charlotte Hornets,Nicolas Batum,5.0,SG,27.0,6-8,200.0,Virginia Commonwealth,13125306.0
Chicago Bulls,Cameron Bairstow,41.0,PF,25.0,6-9,250.0,New Mexico,845059.0
Cleveland Cavaliers,Matthew Dellavedova,8.0,PG,25.0,6-4,198.0,Saint Mary's,1147276.0
Dallas Mavericks,Justin Anderson,1.0,SG,22.0,6-6,228.0,Virginia,1449000.0
Denver Nuggets,Darrell Arthur,0.0,PF,28.0,6-9,235.0,Kansas,2814000.0
Detroit Pistons,Joel Anthony,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
Golden State Warriors,Leandro Barbosa,19.0,SG,33.0,6-3,194.0,North Carolina,2500000.0
Houston Rockets,Trevor Ariza,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
Indiana Pacers,Lavoy Allen,5.0,PF,27.0,6-9,255.0,Temple,4050000.0
Los Angeles Clippers,Cole Aldrich,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
Los Angeles Lakers,Brandon Bass,2.0,PF,31.0,6-8,250.0,LSU,3000000.0
Memphis Grizzlies,Jordan Adams,3.0,SG,21.0,6-5,209.0,UCLA,1404600.0
Miami Heat,Chris Bosh,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
Milwaukee Bucks,Giannis Antetokounmpo,34.0,SF,21.0,6-11,222.0,Arizona,1953960.0
Minnesota Timberwolves,Nemanja Bjelica,88.0,PF,28.0,6-10,240.0,Louisville,3950001.0
New Orleans Pelicans,Alexis Ajinca,42.0,C,28.0,7-2,248.0,California,4389607.0
New York Knicks,Arron Afflalo,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
Oklahoma City Thunder,Steven Adams,12.0,C,22.0,7-0,255.0,Pittsburgh,2279040.0
Orlando Magic,Dewayne Dedmon,3.0,C,26.0,7-0,245.0,USC,947276.0
Philadelphia 76ers,Elton Brand,42.0,PF,37.0,6-9,254.0,Duke,947276.0
Phoenix Suns,Eric Bledsoe,2.0,PG,26.0,6-1,190.0,Kentucky,13500000.0
Portland Trail Blazers,Cliff Alexander,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
Sacramento Kings,Quincy Acy,13.0,SF,25.0,6-7,240.0,Baylor,981348.0
San Antonio Spurs,LaMarcus Aldridge,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
Toronto Raptors,Bismack Biyombo,8.0,C,23.0,6-9,245.0,Missouri,2814000.0
Utah Jazz,Trevor Booker,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
Washington Wizards,Alan Anderson,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0

In [11]:
#accessing the information related to a particular group

teammates.get_group('Los Angeles Lakers')

,Name,Number,Position,Age,Height,Weight,College,Salary
106,Brandon Bass,2.0,PF,31.0,6-8,250.0,LSU,3000000.0
107,Tarik Black,28.0,C,24.0,6-9,250.0,Kansas,845059.0
108,Anthony Brown,3.0,SF,23.0,6-7,210.0,Stanford,700000.0
109,Kobe Bryant,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
110,Jordan Clarkson,6.0,PG,24.0,6-5,194.0,Missouri,845059.0
111,Roy Hibbert,17.0,C,29.0,7-2,270.0,Georgetown,15592217.0
112,Marcelo Huertas,9.0,PG,33.0,6-3,200.0,NaN,525093.0
113,Ryan Kelly,4.0,PF,25.0,6-11,230.0,Duke,1724250.0
114,Larry Nance Jr.,7.0,PF,23.0,6-9,230.0,Wyoming,1155600.0
115,Julius Randle,30.0,PF,21.0,6-9,250.0,Kentucky,3132240.0
116,D'Angelo Russell,1.0,PG,20.0,6-5,195.0,Ohio State,5103120.0
117,Robert Sacre,50.0,C,27.0,7-0,270.0,Gonzaga,981348.0
118,Louis Williams,23.0,SG,29.0,6-1,175.0,NaN,7000000.0
119,Metta World Peace,37.0,SF,36.0,6-7,260.0,St. John's,947276.0
120,Nick Young,0.0,SF,31.0,6-7,210.0,USC,5219169.0

In [12]:
#so we learnt that
# on applying the first groupby command, we actually create an instance(object) of the class(something on similar lines)
#and then we apply get_group to that same object

In [13]:
df = pd.read_csv(r'C:\Users\Administrator\Desktop\Python Test Data\nba.csv')

In [14]:
#splitting based on two parameters

grp = df.groupby(['Team', 'Position'])

In [15]:
grp.first()

                                         Name  Number   Age Height  Weight  \
Team               Position
Atlanta Hawks      C               Al Horford    15.0  30.0   6-10   245.0
                   PF          Kris Humphries    43.0  31.0    6-9   235.0
                   PG         Dennis Schroder    17.0  22.0    6-1   172.0
                   SF           Kent Bazemore    24.0  26.0    6-5   201.0
                   SG        Tim Hardaway Jr.    10.0  24.0    6-6   205.0
...                                       ...     ...   ...    ...     ...
Washington Wizards C            Marcin Gortat    13.0  32.0   6-11   240.0
                   PF             Drew Gooden    90.0  34.0   6-10   250.0
                   PG          Ramon Sessions     7.0  30.0    6-3   190.0
                   SF            Jared Dudley     1.0  30.0    6-7   225.0
                   SG           Alan Anderson     6.0  33.0    6-6   220.0

                                          College      Salary
Team               Position
Atlanta Hawks      C                      Florida  12000000.0
                   PF                   Minnesota   1000000.0
                   PG                 Wake Forest   1763400.0
                   SF                Old Dominion   2000000.0
                   SG                    Michigan   1304520.0
...                                           ...         ...
Washington Wizards C         North Carolina State  11217391.0
                   PF                      Kansas   3300000.0
                   PG                      Nevada   2170465.0
                   SF              Boston College   4375000.0
                   SG              Michigan State   4000000.0

[149 rows x 7 columns]